import Image from "next/image";

const STAGES = [
  {
    number: "01",
    title: "Dairy Cattle & Livestock",
    body: "Everything starts with our herd. Pasture-raised cattle produce fresh milk for market and organic manure as a natural byproduct. No hormones, no antibiotics — just healthy animals living as they should.",
    bullets: ["Pasture-fed, hormone-free herd", "Fresh milk produced daily", "Manure collected and processed on-site"],
    img: "/images/hero/bg-img.png",
    alt: "Dairy cattle at Ingaju Farms",
  },
  {
    number: "02",
    title: "Organic Fertilizer Production",
    body: "Manure doesn't go to waste — it goes to work. We compost and process it into rich organic fertilizer that rebuilds soil health naturally, eliminating the need for synthetic inputs.",
    bullets: ["100% natural composting process", "Replaces synthetic fertilizers entirely", "Improves soil structure and microbial life"],
    img: "/images/dairy/organic-manure.png",
    alt: "Organic manure composting at Ingaju",
  },
  {
    number: "03",
    title: "Crop Production",
    body: "Soil enriched by organic fertilizer grows healthy, chemical-free crops. From corn and beans to macadamia nuts, our diverse produce benefits from naturally fertile ground.",
    bullets: ["Zero synthetic pesticides or fertilizers", "Diverse crop varieties grown year-round", "Higher nutritional value from healthy soil"],
    img: "/images/crops/maiz.jpg",
    alt: "Crops growing at Ingaju Farms",
  },
  {
    number: "04",
    title: "Animal Feed & the Loop Closes",
    body: "Crop residues, husks, and by-products are fed back to the livestock. The herd stays healthy, costs stay low, and the cycle begins again — completely self-sustaining.",
    bullets: ["Crop waste repurposed as animal feed", "Reduces external feed purchasing costs", "Completes the zero-waste loop"],
    img: "/images/dairy/This image illustrates a Full Cycle Circular Economy in Integrated Dairy Farming. It represents a closed-loop system where waste from one stage becomes a valuable resource for another, aiming to maximize productivity and resource efficiency while minimizing environmental impact.

The cycle is broken down into eight interconnected stages that flow clockwise, supported by internal causal linkages.

The 8 Stages of the Circular Cycle
1. Feed Production (Fodder & Forage Crops)
The cycle begins with growing high-quality fodder and forage crops specifically for dairy animals. Excellent crop production acts as the foundation for animal health.

2. Dairy Production
The produced feed goes directly to the livestock. Healthy, well-fed cows produce high-quality milk.

3. Milk Processing
Raw milk from the dairy production stage is processed into value-added consumer dairy products such as yogurt, cheese, and butter. This stage drives market opportunities and farm income.

4. Waste Utilization
Manure and organic waste generated by the cows and processing facilities are collected rather than discarded. This waste is converted via systems like anaerobic digesters into biogas and organic fertilizer, turning a potential pollutant into a resource.

5. Crop Production
The organic fertilizer (nutrients) extracted from the waste utilization stage is applied back to the fields. This improves soil fertility and supports the growth of food crops and fodder.

6. Energy Recovery
The biogas captured during waste utilization is harnessed as a clean energy source. It is used directly on the farm for cooking, heating, generating electricity, and meeting other operational energy needs.

7. Water Reuse
Wastewater from the farming and processing operations is treated and reused. This reclaimed water is used for field irrigation and farm cleaning, conserving fresh water sources.

8. Nutrient Recycling
By returning organic matter and treated water back to the land, nutrients are safely recycled into the soil. This significantly reduces the farm's reliance on costly chemical fertilizers and brings the cycle right back to stage one (Feed Production).

Internal Causal Linkages (The Inner Ring)
The dashed arrows in the center explain the ripple effects and benefits that connect these stages across the loop:

Better feed directly improves animal health and milk productivity.

Value addition increases income and market reach.

Waste becomes a resource, feeding back into the system as fertilizer and energy.

Healthy soil increases crop yield and feed quality.

Renewable energy reduces farm operational costs and carbon emissions.

Water reuse conserves water and reduces local pollution.

Nutrient recycling improves overall soil fertility and lowers input costs.cow-feed.png",
    alt: "Livestock being fed at Ingaju",
  },
];

export default function CircularStages() {
  return (
    <section className="w-full bg-white">
      <div className="container-pad py-24">

        <div className="text-center mb-16">
          <p className="text-sm font-body font-semibold tracking-widest uppercase text-[#3A7D5A] mb-3">Deep Dive</p>
          <h2 className="font-heading text-3xl font-bold text-[#1C2321] sm:text-4xl">
            The Four Stages <span className="text-[#3A7D5A]">Explained</span>
          </h2>
          <p className="mt-4 max-w-xl mx-auto text-[15px] font-body leading-relaxed text-[#6B6259]">
            Every stage feeds the next. Nothing leaves the system — everything becomes something else.
          </p>
        </div>

        <div className="grid grid-cols-1 gap-6 sm:grid-cols-2">
          {STAGES.map(({ number, title, body, bullets, img, alt }) => (
            <div key={number} className="flex flex-col rounded-3xl overflow-hidden bg-[#F8F6F2] border border-[#1C2321]/5">
              {/* Image */}
              <div className="relative h-70 w-full overflow-hidden">
                <Image src={img} alt={alt} fill sizes="(min-width:1024px) 25vw, (min-width:640px) 50vw, 100vw" className="object-cover" />
                {/* Number overlay */}
                <div className="absolute top-4 left-4 flex items-center justify-center w-9 h-9 rounded-full bg-[#0a0f0d]/60 backdrop-blur-sm border border-white/20">
                  <span className="font-heading text-xs font-bold text-white">{number}</span>
                </div>
              </div>

              {/* Content */}
              <div className="flex flex-col flex-1 p-6 border-t-2 border-[#3A7D5A]">
                <h3 className="font-heading text-lg font-bold text-[#1C2321] leading-snug">{title}</h3>
                <p className="mt-3 text-sm font-body text-[#6B6259] leading-relaxed">{body}</p>
                <ul className="mt-5 space-y-2">
                  {bullets.map((point) => (
                    <li key={point} className="flex items-start gap-2.5 text-sm font-body text-[#6B6259]">
                      <span aria-hidden className="mt-2 h-1.5 w-1.5 flex-shrink-0 rounded-full bg-[#3A7D5A]" />
                      {point}
                    </li>
                  ))}
                </ul>
              </div>
            </div>
          ))}
        </div>

      </div>
    </section>
  );
}
